[package]
name = "simple_tcp"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
derive_more = {version = "0.99.18", features =["from", "display"]}
env_logger = "0.11.3"
log = "0.4.21"
serde = "1.0.203"
